#!/bin/sh
[ ! -e /dev/console ] && mknod /dev/console c 5 1
[ ! -e /dev/tty2 ]    && mknod /dev/tty2 c 4 2
[ ! -e /dev/tty3 ]    && mknod /dev/tty3 c 4 3
[ ! -e /dev/tty4 ]    && mknod /dev/tty4 c 4 4
[ ! -e /dev/ram ]     && mknod /dev/ram b 1 1
[ ! -e /dev/mem ]     && mknod /dev/mem c 1 1
[ ! -e /dev/kmem ]    && mknod /dev/kmem c 1 2
[ ! -e /dev/null ]    && mknod /dev/null c 1 3
[ ! -e /dev/zero ]    && mknod /dev/zero c 1 5
mount -t proc none /proc
mount -t sysfs none /sys
