#!/bin/bash
##############################################################################
# Copyright (c) 2012 Mark Charlebois
# Copyright (c) 2012 Behan Webster
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to 
# deal in the Software without restriction, including without limitation the 
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or 
# sell copies of the Software, and to permit persons to whom the Software is 
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in 
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
##############################################################################

if [ -z "$GCCHOME" ]; then
	GCCHOME=${CSCC_DIR:-/opt}
fi

if [ -z "$CSVERSION" ]; then
	# Use Code Sourcery arm-2011.03 by default
	CSVERSION=2011.03
	GCCVERSION=4.5.2
fi

export CSCC_DIR=${CSCC_DIR:-$GCCHOME/arm-$CSVERSION}
export CSCC_BINDIR=${CSCC_BINDIR:-$CSCC_DIR/bin}
export HOST_TYPE=${HOST_TYPE:-arm-none-linux-gnueabi}
export HOST_TRIPLE=${HOST_TRIPLE:-arm-none-gnueabi}

if [ ! -d $CSCC_DIR ]; then
		echo "Compiler not found: $CSCC_DIR"
		exit 1
fi

export COMPILER_PATH=$CSCC_DIR
export CROSS_COMPILE=$HOST_TYPE-
export CC_FOR_BUILD=$CSCC_BINDIR/$HOST_TYPE-gcc
